### ISSUE TITLE
ZOD error on "Using the Tailwind CSS Palette Generator and API"

### ISSUE THREAD

**Issue by gordysc** [SimeonGriggs/simeonGriggs#3]
Really enjoy using your Tailwind CSS Palette Generator! Was going to read more on how the "Add" method works (if it just picks a random color or is using color theory for picking the next color), but looks like the blog post describing how it works throws a ZOD error? 

URL: https://www.simeongriggs.dev/using-the-tailwind-css-palette-generator-and-api

```sh
ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "null",
    "path": [
      "link",
      "reference"
    ],
    "message": "Expected object, received null"
  }
]
    at Re (https://www.simeongriggs.dev/build/_shared/chunk-KYXJMCSM.js:1:7398)
    at _.safeParse (https://www.simeongriggs.dev/build/_shared/chunk-KYXJMCSM.js:1:9637)
    at _.parse (https://www.simeongriggs.dev/build/_shared/chunk-KYXJMCSM.js:1:9317)
    at https://www.simeongriggs.dev/build/_shared/chunk-QXKXZYM4.js:4:20158
    at Object.useMemo (https://www.simeongriggs.dev/build/_shared/chunk-P2YMVDBK.js:6:25754)
    at r.useMemo (https://www.simeongriggs.dev/build/_shared/chunk-NJBA5JVR.js:1:6135)
    at Ot (https://www.simeongriggs.dev/build/_shared/chunk-QXKXZYM4.js:4:20143)
    at du (https://www.simeongriggs.dev/build/_shared/chunk-P2YMVDBK.js:6:19484)
    at Ba (https://www.simeongriggs.dev/build/_shared/chunk-P2YMVDBK.js:8:44019)
    at Ua (https://www.simeongriggs.dev/build/_shared/chunk-P2YMVDBK.js:8:39724)
```

**Comment by SimeonGriggs** [comment]
Ooooops that's my bad. Fixed now!

**Comment by gordysc** [comment]
Thank you!!
